language: ru

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  case_sensitive: false
  use_word_boundaries: true
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 2

# Подключение предобученной модели трансформера (BERT)
- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "bert-base-cased"
  cache_dir: null

- name: DIETClassifier
  epochs: 50
  batch_strategy: "sequence"
  similarity_type: "inner"
  maximum_positive_similarity: 0.9
  maximum_negative_similarity: 0
  constrain_similarities: true
  model_confidence: "softmax"
  ranking_length: 3
  entity_recognition: false
  evaluate_every_number_of_epochs: -1
  use_masked_language_model: true

- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 1

policies:
- name: MemoizationPolicy
  max_history: 2
- name: RulePolicy
- name: TEDPolicy
  max_history: 2
  epochs: 1
  constrain_similarities: true
assistant_id: 20250213-195755-one-duplet